version: "3"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
  adminer:
    build:
      context: .
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_DRIVER: pgsql
    ports:
      - 8080:8080
    depends_on:
      - db
